In [43]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [44]:
# load the train midel , scaler pickle , onehot
model = load_model('model.h5')

# load encoder and scaler
with open('label_encoder_gender.pkl' , 'rb')as file:
    label_encoder_gender = pickle.load(file)

with open('onehot_encoder_geography.pkl' , 'rb')as file:
    onehot_encoder_geography = pickle.load(file)

with open('scaler.pkl' , 'rb')as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [45]:
input_data = {
    "CreditScore": 539,
    "Geography": "France",
    "Gender": "Male",
    "Age": 37,
    "Tenure": 2,
    "Balance": 127609.59,
    "NumOfProducts": 1,
    "HasCrCard": 1,
    "IsActiveMember": 0,
    "EstimatedSalary": 98646.22
}

In [46]:
geo_encoded = onehot_encoder_geography.transform([[input_data['Geography']]])
geo_encoded_df = pd.DataFrame(geo_encoded , columns=onehot_encoder_geography.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\YASH JAIN\Documents\New Folder\OneDrive\Desktop\Data Science\Deep_Learning\projects\p1\myenv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [47]:
input_data = pd.DataFrame([input_data])
input_data=pd.concat([input_data.reset_index(drop=True) , geo_encoded_df] , axis=1)
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,539,France,Male,37,2,127609.59,1,1,0,98646.22,1.0,0.0,0.0

In [48]:
input_data['Gender'] = label_encoder_gender.transform(input_data['Gender'])

In [49]:
input_data.drop(['Geography'] , axis=1 , inplace=True)
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,539,1,37,2,127609.59,1,1,0,98646.22,1.0,0.0,0.0

In [50]:
# scaling the input data
input_scale = scaler.transform(input_data)
input_scale

array([[-1.16902675,  0.91324755, -0.18042372, -1.04241787,  0.82468525,
        -0.91668767,  0.64920267, -1.02583358, -0.03103642,  1.00150113,
        -0.57946723, -0.57638802]])

In [51]:
prediction = model.predict(input_scale)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 265ms/step

array([[0.14999457]], dtype=float32)

In [52]:
prediction_probablity = prediction[0]
prediction_probablity

array([0.14999457], dtype=float32)

In [54]:
if prediction_probablity > 0.5:
    print('the customer is likely to chur.')

else:
    print('The customer is not likely to churn')

The customer is not likely to churn